# This file was generated by GoReleaser. DO NOT EDIT.
cask "canticle" do
  version "1.24.1"

  on_macos do
    on_intel do
      sha256 "e260ddec8e2b05a349c5988c3ddd1d211236fc8b547d58d8170c4f2ff95ffd2c"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5cdabb1e48bd71dadb34a5455970ddfae54afeee5b13ef78758fb80454c18ea"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4405bb4630ef4cd8c6298b5a2a11f5847c484678f95b34d4c08dec717cba70e4"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c068e44f4a33888bdb72897955e8745024d88c99bcf93eb3e2f433558f1e02a"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canticle"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "mxlrcgo-svc",
    ]

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
