# This file was generated by GoReleaser. DO NOT EDIT.
cask "canticle" do
  version "1.12.0"

  on_macos do
    on_intel do
      sha256 "fd62f24872961622fb027651a46fdc726333f4732a3559bacf5853b1f2aaeb32"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b79137d77e2d2f97cc3fe3132eae93307bb60a23b75774205516aafc5137da9b"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5223e2ee1374ab0f493303c5d208b447274d8f4e3b9644a4c964f39a351c82c5"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d760e3eb1d6ba8715f3ca2048ca4d85da63e1c4568bbe779a9eb69224712f08"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canticle"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://doxazo-net.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "mxlrcgo-svc",
    ]

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
