# This file was generated by GoReleaser. DO NOT EDIT.
cask "canticle" do
  version "1.18.0"

  on_macos do
    on_intel do
      sha256 "466f7b39f70a15b48898f50a2716c036ad03bcb22cc3f46244c5cfa12b62a239"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "27eda02abd735df23cdfe6d3004bf3ba0b78331268cab7cca668768ab4af45d9"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "efcee240409894d13d59c5b4104d94da5545b4ba9c785b8d9a997c0c875d8c25"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a89c73d858320ac70bdad7af9f5a20a7c713cef070d59c909c2060f0a3cb31bc"
      url "https://github.com/doxazo-net/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canticle"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://doxazo-net.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "mxlrcgo-svc",
    ]

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
