# This file was generated by GoReleaser. DO NOT EDIT.
cask "mxlrcgo-svc" do
  version "1.9.1"

  on_macos do
    on_intel do
      sha256 "d8a88ef720f66b788a2eb42dda6ffd46a5977225dc87857ef79e2170cbc2f945"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a4d559e2ac1a98b8e9e3758121718059fa90a325935881b4db69ca9ebfc1c84"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2472ddc2e9a2ecab6a1a4ee5abbf1ca98d42e814afd4477528e4727bf511df60"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b3fe85515655db51aeb69e21bae1841a5bc72d57626bccd573da043b0c80085"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mxlrcgo-svc"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
