# This file was generated by GoReleaser. DO NOT EDIT.
cask "mxlrcgo-svc" do
  version "1.8.1"

  on_macos do
    on_intel do
      sha256 "85ff7057f6895398a94b0194e1700691e0369e3db28fb408dd6e78bbd1bebf44"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d70eb69288f2d81598ad06d4237fc0fc5a0753f80dfa8ecf4f5371ac98c6596"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ad40dc388e83cf8c04719922093ab1d4ec7eff77eba321f5a92992473171d3a"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67e1ff98cfc047d3b60a38afb7752a045fa5834f1de01db3a238102898b171bb"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mxlrcgo-svc"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
