# This file was generated by GoReleaser. DO NOT EDIT.
cask "mxlrcgo-svc" do
  version "1.7.0"

  on_macos do
    on_intel do
      sha256 "b9e698ff87dc8576a9d87f58a9a01a359b49506faf00d8fbbf8358f0928ecc65"
      url "https://github.com/sydlexius/mxlrcgo-svc/releases/download/v#{version}/mxlrcgo-svc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ffec97858a24acb60fb1d1a466ed1cc9dd16198a0575cb71a80c11eb722ef1d"
      url "https://github.com/sydlexius/mxlrcgo-svc/releases/download/v#{version}/mxlrcgo-svc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "072c0a87b3cadd2dcc27561590a9dfc39d3f5711db6ca0d1bfd55ab94b48be38"
      url "https://github.com/sydlexius/mxlrcgo-svc/releases/download/v#{version}/mxlrcgo-svc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88cc105fb38680bc8f7b83b7e78a18667839ed0b95fff5edb1c06e075f06c486"
      url "https://github.com/sydlexius/mxlrcgo-svc/releases/download/v#{version}/mxlrcgo-svc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mxlrcgo-svc"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/mxlrcgo-svc/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mxlrcgo-svc"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
